import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from torch.nn.utils.rnn import pad_sequence
from collections import defaultdict

data = [
    ("MHAKCS", "MHACKS"),
    ("MHACSK", "MHACKS"),
    ("MHCAKS", "MHACKS"),
    ("MHACKS", "MHACKS"),
    ("MHAKCS", "MHACKS"),
    ("MHACSKS", "MHACKS"),
    ("MHACK", "MHACKS"),
    ("MHACSKS", "MHACKS"),
    ("MHAKC", "MHACKS"),
    ("MHACKSY", "MHACKS"),
    ("HELLOORLD", "HELLO WORLD"),
    ("HELLOWOLRD", "HELLO WORLD"),
    ("HELLO WORLD", "HELLO WORLD"),
    ("HELLOWORLD", "HELLO WORLD"),
    ("HELLOWORL", "HELLO WORLD"),
    ("HLELO WORLD", "HELLO WORLD"),
    ("HLOEL WORLD", "HELLO WORLD"),
    ("HELLOWROLD", "HELLO WORLD"),
    ("HELLO WRLD", "HELLO WORLD"),
    ("HELLO WROLD", "HELLO WORLD"),
    ("HELLO WOLD", "HELLO WORLD"),
    ("HLOOWORLD", "HELLO WORLD"),
    ("HELLOWRL", "HELLO WORLD"),
    ("HELLO WROLD", "HELLO WORLD"),
    ("HLLLO WORLD", "HELLO WORLD"),
    ("HLLLOORLD", "HELLO WORLD"),
    ("HELLOOWORLD", "HELLO WORLD"),
    ("HLELO WOLRD", "HELLO WORLD"),
    ("HELLOWORLD", "HELLO WORLD"),
    ("HLLWORLD", "HELLO WORLD"),
    ("HLLWRLD", "HELLO WORLD"),
    ("GO BULE", "GO BLUE"),
    ("GO BLU", "GO BLUE"),
    ("GO BLEW", "GO BLUE"),
    ("GO BULEE", "GO BLUE"),
    ("GOBLUE", "GO BLUE"),
    ("GO BLUEE", "GO BLUE"),
    ("GOBLUEE", "GO BLUE"),
    ("GO BLLUE", "GO BLUE"),
    ("GO BOLUE", "GO BLUE"),
    ("GO BLUUE", "GO BLUE"),
    ("GO BULED", "GO BLUE"),
    ("GOBU", "GO BLUE"),
    ("GOBLU", "GO BLUE"),
    ("GOBLUU", "GO BLUE"),
    ("GO BLAUE", "GO BLUE"),
    ("GOBLUW", "GO BLUE"),
    ("GO BLUES", "GO BLUE"),
    ("GO BLUU", "GO BLUE"),
]


# data = [
#     ("THERAINDROPPEDFAST", "THE RAIN DROPPED FAST"),
#     ("HELLOFROMTHEOTHERSIDE", "HELLO FROM THE OTHER SIDE"),
#     ("WEATHERISGOODTODAY", "WEATHER IS GOOD TODAY"),
#     ("HOWAREYOUTODAY", "HOW ARE YOU TODAY"),
#     ("SHEWENTTOTHEMARKET", "SHE WENT TO THE MARKET"),
#     ("ICANTBELIEVEIT", "I CAN'T BELIEVE IT"),
#     ("LETSGETSTARTED", "LET'S GET STARTED"),
#     ("DONTWORRYBEHAPPY", "DON'T WORRY BE HAPPY"),
#     ("WELCOMETOTHEPARTY", "WELCOME TO THE PARTY"),
#     ("THEROADISLONGANDWINDING", "THE ROAD IS LONG AND WINDING"),
#     ("ITWASALOVELYSUNNYDAY", "IT WAS A LOVELY SUNNY DAY"),
#     ("RUNNINGINTHEMORNING", "RUNNING IN THE MORNING"),
#     ("STAYSAFEANDTAKECARE", "STAY SAFE AND TAKE CARE"),
#     ("THANKYOUFORTHEHELP", "THANK YOU FOR THE HELP"),
#     ("IWILLSEEYOUTOMORROW", "I WILL SEE YOU TOMORROW"),
#     ("THECATJUMPEDOVERTHEDOG", "THE CAT JUMPED OVER THE DOG"),
#     ("YOULOOKGREATTODAY", "YOU LOOK GREAT TODAY"),
#     ("NEVERGIVEUPONTHEM", "NEVER GIVE UP ON THEM"),
#     ("SUCCESSISNOTFARAWAY", "SUCCESS IS NOT FAR AWAY"),
#     ("LIFECANBEBEAUTIFUL", "LIFE CAN BE BEAUTIFUL"),
#     ("SOMETIMESYOUMUSTWAIT", "SOMETIMES YOU MUST WAIT"),
#     ("HELPTHEMWHENYOUCAN", "HELP THEM WHEN YOU CAN"),
#     ("BELIEVEINYOURSELF", "BELIEVE IN YOURSELF"),
#     ("STAYPOSITIVEANDSTRONG", "STAY POSITIVE AND STRONG"),
#     ("GOODTHINGSARECOMING", "GOOD THINGS ARE COMING"),
#     ("DONOTFORGETTHEKEY", "DO NOT FORGET THE KEY"),
#     ("ITISANIMPORTANTTASK", "IT IS AN IMPORTANT TASK"),
#     ("THECUPISFULLOFTEA", "THE CUP IS FULL OF TEA"),
#     ("EXPLORINGNEWIDEASDAILY", "EXPLORING NEW IDEAS DAILY"),
#     ("THEWORLDISFULLWITHWONDER", "THE WORLD IS FULL WITH WONDER"),
#     ("IMAGINEALLTHEPEOPLE", "IMAGINE ALL THE PEOPLE"),
#     ("HOLDONTOTHEDREAM", "HOLD ON TO THE DREAM"),
#     ("NEVERSTOPLEARNING", "NEVER STOP LEARNING"),
#     ("TOMORROWISANOTHERDAY", "TOMORROW IS ANOTHER DAY"),
#     ("ACHIEVEMENTREQUIRESHARDWORK", "ACHIEVEMENT REQUIRES HARD WORK"),
#     ("HAPPINESSISWITHINYOU", "HAPPINESS IS WITHIN YOU"),
#     ("DREAMBIGWORKHARD", "DREAM BIG WORK HARD"),
#     ("PERSISTENCEMATTERSTOO", "PERSISTENCE MATTERS TOO"),
#     ("KEEPUPTHEGOODWORK", "KEEP UP THE GOOD WORK"),
#     ("SHAREKINDNESSEVERYDAY", "SHARE KINDNESS EVERYDAY"),
#     ("YOUDESERVETHEBEST", "YOU DESERVE THE BEST"),
#     ("KNOWLEDGEISPOWER", "KNOWLEDGE IS POWER"),
#     ("SUCCESSBELONGSTOTHOSEWHOPERSEVERE", "SUCCESS BELONGS TO THOSE WHO PERSEVERE"),
#     ("EVERYTHINGSTARTSWITHANIDEA", "EVERYTHING STARTS WITH AN IDEA"),
#     ("THEFUTUREISBRIGHT", "THE FUTURE IS BRIGHT"),
#     ("FOCUSONYOURGOALS", "FOCUS ON YOUR GOALS"),
#     ("PATIENCEISKEYTOGROWTH", "PATIENCE IS KEY TO GROWTH"),
#     ("UNDERSTANDINGBRINGSHARMONY", "UNDERSTANDING BRINGS HARMONY"),
#     ("WORKHARDSTAYHUMBLE", "WORK HARD STAY HUMBLE"),
#     ("CONFIDENCELEADSTOSUCCESS", "CONFIDENCE LEADS TO SUCCESS"),
#     ("NEVERSTOPIMPROVING", "NEVER STOP IMPROVING"),
#     ("SMALLSTEPSLEADTOBIGCHANGE", "SMALL STEPS LEAD TO BIG CHANGE"),
#     ("EVERYDAYISANEWBEGINNING", "EVERY DAY IS A NEW BEGINNING"),
#     ("CHALLENGESMAKEYOUSTRONGER", "CHALLENGES MAKE YOU STRONGER"),
#     ("OPPORTUNITIESAREEVERYWHERE", "OPPORTUNITIES ARE EVERYWHERE"),
#     ("RESPECTOTHERSTOBERESPECTED", "RESPECT OTHERS TO BE RESPECTED"),
#     ("COURAGEISCONTAGIOUS", "COURAGE IS CONTAGIOUS"),
#     ("PERSEVERANCEMOVESMOUNTAINS", "PERSEVERANCE MOVES MOUNTAINS"),
#     ("POSITIVETHINKINGCHANGESLIVES", "POSITIVE THINKING CHANGES LIVES"),
#     ("EVERYPROBLEMHASASOLUTION", "EVERY PROBLEM HAS A SOLUTION"),
#     ("LOVEISALLAROUNDYOU", "LOVE IS ALL AROUND YOU"),
#     ("TEAMWORKMAKESDREAMSWORK", "TEAMWORK MAKES DREAMS WORK"),
#     ("THEJOURNEYISASIMPORTANTASTHEDESINATION", "THE JOURNEY IS AS IMPORTANT AS THE DESTINATION"),
#     ("LEARNINGFROMFAILUREISKEYTOSUCCESS", "LEARNING FROM FAILURE IS KEY TO SUCCESS"),
#     ("STARTSMALLTHINKBIG", "START SMALL THINK BIG"),
#     ("BEYOURSELFANDYOULLSHINE", "BE YOURSELF AND YOU'LL SHINE"),
#     ("LEARNANDGROWWITHGRATITUDE", "LEARN AND GROW WITH GRATITUDE"),
#     ("OPENDYOURMINDTONEWPOSSIBILITIES", "OPEN YOUR MIND TO NEW POSSIBILITIES"),
#     ("THEUNIVERSEISFULLPOTENTIAL", "THE UNIVERSE IS FULL OF POTENTIAL"),
#     ("INNOVATIONSTARTSWITHCREATIVITY", "INNOVATION STARTS WITH CREATIVITY"),
#     ("THENIGHTISDARKESTBEFOREDAWN", "THE NIGHT IS DARKEST BEFORE DAWN"),
#     ("ONESTEPCLOSERTOSUCCESS", "ONE STEP CLOSER TO SUCCESS"),
#     ("NEVERLOOKBACKONLYFORWARD", "NEVER LOOK BACK ONLY FORWARD"),
#     ("CELEBRATEYOURACHIEVEMENTS", "CELEBRATE YOUR ACHIEVEMENTS"),
#     ("FINDJOYINLITTLETHINGS", "FIND JOY IN LITTLE THINGS"),
#     ("GREATTHINGSAREYETTOCOME", "GREAT THINGS ARE YET TO COME"),
#     ("HELLOHOWAREYOU", "HELLO HOW ARE YOU"),
#     ("IAMGOODTHANKYOU", "I AM GOOD THANK YOU"),
#     ("WHATISYOURNAME", "WHAT IS YOUR NAME"),
#     ("MYNAMEISJOHN", "MY NAME IS JOHN"),
#     ("NICE TO MEET YOU", "NICE TO MEET YOU"),
#     ("HOWWASYOURDAY", "HOW WAS YOUR DAY"),
#     ("MYDAYWASGREAT", "MY DAY WAS GREAT"),
#     ("SEYOUSOON", "SEE YOU SOON"),
#     ("IWILLTALKTOYOULATER", "I WILL TALK TO YOU LATER"),
#     ("IAMFEELINGHUNGRY", "I AM FEELING HUNGRY"),
#     ("DOYOUWANTFOOD", "DO YOU WANT FOOD"),
#     ("LETSGOTOEAT", "LET'S GO TO EAT"),
#     ("WHEREISTHERESRESTAURANT", "WHERE IS THE RESTAURANT"),
#     ("ITISOVERTHERE", "IT IS OVER THERE"),
#     ("CANIGETCOFFEE", "CAN I GET COFFEE"),
#     ("IWANTTOWATCHAMOVIE", "I WANT TO WATCH A MOVIE"),
#     ("WHATMOVIESDOYOULIKE", "WHAT MOVIES DO YOU LIKE"),
#     ("LETMEKNOW", "LET ME KNOW"),
#     ("IDONTUNDERSTAND", "I DON'T UNDERSTAND"),
#     ("PLEASESAYTHATAGAIN", "PLEASE SAY THAT AGAIN"),
#     ("IDONTHAVEENOUGHTIME", "I DON'T HAVE ENOUGH TIME"),
#     ("LETSMEETTOMORROW", "LET'S MEET TOMORROW"),
#     ("WHENAREYOUFREE", "WHEN ARE YOU FREE"),
#     ("IAMAVAILABLEATNOON", "I AM AVAILABLE AT NOON"),
#     ("WHATISTODAYSPLAN", "WHAT IS TODAY'S PLAN"),
#     ("DOYOUHAVEANYQUESTIONS", "DO YOU HAVE ANY QUESTIONS"),
#     ("WHEREAREYOUGOING", "WHERE ARE YOU GOING"),
#     ("IMGOINGTOTHESTORE", "I'M GOING TO THE STORE"),
#     ("WHICHWAYSHOULDITAKE", "WHICH WAY SHOULD I TAKE"),
#     ("TURNLEFTATTHENEXTLIGHT", "TURN LEFT AT THE NEXT LIGHT"),
#     ("IDLIKETOHAVEAPIZZA", "I'D LIKE TO HAVE A PIZZA"),
#     ("PLEASEPASSMETHESALT", "PLEASE PASS ME THE SALT"),
#     ("DOYOUKNOWHERNAME", "DO YOU KNOW HER NAME"),
#     ("IWILLTEXTHERLATER", "I WILL TEXT HER LATER"),
#     ("LETSCALLNOW", "LET'S CALL NOW"),
#     ("WHENISTHEPARTY", "WHEN IS THE PARTY"),
#     ("THEPARTYISTONIGHT", "THE PARTY IS TONIGHT"),
#     ("WHATTIMEISITNOW", "WHAT TIME IS IT NOW"),
#     ("ITISFOUROCLOCK", "IT IS FOUR O'CLOCK"),
#     ("IHAVETOLEAVESOON", "I HAVE TO LEAVE SOON"),
#     ("SEEOUYOUNEXTTIME", "SEE YOU NEXT TIME"),
#     ("CANYOUDOTHAT", "CAN YOU DO THAT"),
#     ("IWILLTRYMYBEST", "I WILL TRY MY BEST"),
#     ("HOWDOYOUFEEL", "HOW DO YOU FEEL"),
#     ("IAMHAPPYRIGHTNOW", "I AM HAPPY RIGHT NOW"),
#     ("IWASBUSYTODAY", "I WAS BUSY TODAY"),
#     ("CANYOUSPEAKSLOWER", "CAN YOU SPEAK SLOWER"),
#     ("THATSOKAYITHAPPENS", "THAT'S OKAY IT HAPPENS"),
#     ("ITISALLRIGHT", "IT IS ALL RIGHT"),
#     ("YOUAREWELCOME", "YOU ARE WELCOME"),
#     ("THANKYOUVERYMUCH", "THANK YOU VERY MUCH"),
#     ("WEREYOUATHOME", "WERE YOU AT HOME"),
#     ("IDONTKNOW", "I DON'T KNOW"),
#     ("LETSSTARTTHEMEETING", "LET'S START THE MEETING"),
#     ("PLEASEHURRYUP", "PLEASE HURRY UP"),
#     ("ICANTFINDMYPHONE", "I CAN'T FIND MY PHONE"),
#     ("CANYOUHELPMEMOVE", "CAN YOU HELP ME MOVE"),
#     ("IAGREEWITHYOU", "I AGREE WITH YOU"),
#     ("IWILLBETHERESOON", "I WILL BE THERE SOON"),
#     ("CANICOMEWITHYOU", "CAN I COME WITH YOU"),
#     ("HOWLONGWILLITTAKE", "HOW LONG WILL IT TAKE"),
#     ("ILLSEEYOUINAFEWMINUTES", "I'LL SEE YOU IN A FEW MINUTES"),
#     ("WHATDIDYOUSAY", "WHAT DID YOU SAY"),
#     ("IHAVEANEWIDEA", "I HAVE A NEW IDEA"),
#     ("LETSWORKTOGETHER", "LET'S WORK TOGETHER"),
#     ("WHATSHOULDIDONEXT", "WHAT SHOULD I DO NEXT"),
#     ("PLEASEREMINDME", "PLEASE REMIND ME"),
#     ("WHEREISTHEBATHROOM", "WHERE IS THE BATHROOM"),
#     ("ILLBEBACKSOON", "I'LL BE BACK SOON"),
#     ("PLEASEREADTHISFORME", "PLEASE READ THIS FOR ME"),
#     ("ITSALMOSTTIME", "IT'S ALMOST TIME"),
#     ("THEREISAPROBLEM", "THERE IS A PROBLEM"),
#     ("THATSANEASYFIX", "THAT'S AN EASY FIX"),
#     ("WEREYOULATE", "WERE YOU LATE"),
#     ("INEEDHELPNOW", "I NEED HELP NOW"),
#     ("ICANNOTFINDIT", "I CANNOT FIND IT"),
#     ("CANIGETYOURATTENTION", "CAN I GET YOUR ATTENTION"),
#     ("WHATISTHEPRICE", "WHAT IS THE PRICE"),
#     ("ILLPAYFORIT", "I'LL PAY FOR IT"),
#     ("LETSPLANTHEVACATION", "LET'S PLAN THE VACATION"),
#     ("IWILLDRIVEUS", "I WILL DRIVE US"),
#     ("HOWFARISIT", "HOW FAR IS IT"),
#     ("ITSABOUTONEMILE", "IT'S ABOUT ONE MILE"),
#     ("WEDESERVEBREAK", "WE DESERVE A BREAK"),
#     ("IMTHIRSTY", "I'M THIRSTY"),
#     ("ITSGETTINGLATE", "IT'S GETTING LATE"),
#     ("IDONTLIKETHIS", "I DON'T LIKE THIS"),
#     ("IMSOEXCITED", "I'M SO EXCITED"),
#     ("PLEASEREPEATTOTHIS", "PLEASE REPEAT THIS"),
#     ("CANIPLAYWITHYOU", "CAN I PLAY WITH YOU"),
#     ("LETSGETGOING", "LET'S GET GOING"),
#     ("ITSBEAUTIFULDAY", "IT'S A BEAUTIFUL DAY"),
#     ("WHATISWEATHERLIKETODAY", "WHAT IS THE WEATHER LIKE TODAY"),
#     ("CANYOUTELLMEASTORY", "CAN YOU TELL ME A STORY"),
#     ("THISLOOKSINTERESTING", "THIS LOOKS INTERESTING"),
#     ("CANYOUPASSMETHEWATER", "CAN YOU PASS ME THE WATER"),
#     ("THEREISNOMOREFOODLEFT", "THERE IS NO MORE FOOD LEFT"),
#     ("ICANTWAITTOSEEYOU", "I CAN'T WAIT TO SEE YOU"),
#     ("ISTHISTHECORRECTWAY", "IS THIS THE CORRECT WAY"),
#     ("YOUARELOOKINGGREAT", "YOU ARE LOOKING GREAT"),
#     ("THISISSOMETHINGNEW", "THIS IS SOMETHING NEW"),
#     ("IAMRUNNINGLATE", "I AM RUNNING LATE"),
#     ("THANKSFORYOURTIME", "THANKS FOR YOUR TIME"),
#     ("LETSBEGINNOW", "LET'S BEGIN NOW"),
#     ("IAMNOTSUREABOUTTHIS", "I AM NOT SURE ABOUT THIS"),
#     ("CANICALLYOUTOMORROW", "CAN I CALL YOU TOMORROW"),
#     ("THISLOOKSGOODTOME", "THIS LOOKS GOOD TO ME"),
#     ("IWANTTOASKYOUQUESTION", "I WANT TO ASK YOU A QUESTION"),
#     ("LETSSTARTOVER", "LET'S START OVER"),
#     ("HELLOWORLD", "HELLO WORLD"),
#     ("ILOVEMHACKS", "I LOVE MHACKS"),
# ]

vocab = set("ABCDEFGHIJKLMNOPQRSTUVWXYZ '")
char_to_idx = {char: idx for idx, char in enumerate(sorted(vocab))}
idx_to_char = {idx: char for char, idx in char_to_idx.items()}
#print(f"Vocabulary size: {len(char_to_idx)}")

def encode_sequence(sequence, char_to_idx):
    encoded = []
    for char in sequence:
        if char in char_to_idx:
            encoded.append(char_to_idx[char])
        else:
            raise ValueError(f"Character '{char}' is not in the vocabulary.")
    return encoded

def get_dataset():
    encoded_inputs = []
    encoded_outputs = []

    for input_seq, output_seq in data:
        input_encoded = encode_sequence(input_seq, char_to_idx)
        output_encoded = encode_sequence(output_seq, char_to_idx)

        while len(output_encoded) < len(input_encoded):
            output_encoded.append(char_to_idx[' '])

        max_length = max(len(input_encoded), len(output_encoded))
        input_encoded = input_encoded + [0] * (max_length - len(input_encoded))
        output_encoded = output_encoded + [0] * (max_length - len(output_encoded))

        encoded_inputs.append(torch.tensor(input_encoded))
        encoded_outputs.append(torch.tensor(output_encoded))
    
    print(f"Input sequence length: {len(input_encoded)}, Output sequence length: {len(output_encoded)}")

    padded_inputs = pad_sequence(encoded_inputs, batch_first=True, padding_value=char_to_idx[' '])
    padded_outputs = pad_sequence(encoded_outputs, batch_first=True, padding_value=char_to_idx[' '])

    print(f"Padded inputs shape: {padded_inputs.shape}")
    print(f"Padded outputs shape: {padded_outputs.shape}")

    return padded_inputs.long(), padded_outputs.long()

if __name__ == "__main__":
    inputs, outputs = get_dataset()
    print(f"Sample encoded input: {inputs[0]}")
    print(f"Sample encoded output: {outputs[0]}")
   # print(f"Vocabulary: {char_to_idx}")
